### ISSUE TITLE
Password Hashing

### ISSUE THREAD

**Issue by tiagoduarte21** [ravemir/meo-wifi-login#5]
Hey there,

MEO-WiFi is now hashing the passwords on login.
It's no longer possible to login with plain text.
Is there anyway we can avoid this in your script?

Thank you!

**Comment by joaormatos** [comment]
They're actually encrypting the password using the client's LAN IP address to derive the key (you know, the one your network interface got when you connected to their access points).
 
Here's what they do:
1. Get the IP address of the client from a separate AJAX request after loading the page
2. Derive a key from the IP address using PBKDF2
3. Encrypt the password using AES and the key derived above
4. Use the base64-encoded ciphertext in place of the password

PBKDF2 parameters: SHA1, 100 iterations, 256 bit keysize, fixed salt 
AES parameters: CBC, 256 bit, PKCS#7 padding, fixed IV

I'm just about done implementing this weird encryption scheme in Python and will update later.

I'm curious as to what they were trying to do with this change.

It doesn't really improve the cryptographic strength of the login process (as all the material needed to recover the password is trivially accessible to any attacker that can capture the ciphertext) and it doesn't significantly increase the computational cost for attackers trying to crack a user's password (the PBKDF2 only needs to run once per IP address and is pretty short, to boot.)

**Comment by joaormatos** [comment]
Here's a python implementation of their Encrypt function:

```python
#!/usr/bin/env python
import hashlib, base64
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.padding import PKCS7
from cryptography.hazmat.backends import default_backend

def pad_password(password):
    padder = PKCS7(16*8).padder()
    return padder.update(password.encode("utf8")) + padder.finalize()

def encrypt_password(ip, password):
    # Convert iv and salt strings into byte arrays
    salt = bytearray.fromhex("77232469666931323429396D656F3938574946")
    iv = bytearray.fromhex("72c4721ae01ae0e8e84bd64ad66060c4")

    # Generate key from IP address
    key = hashlib.pbkdf2_hmac("sha1", ip.encode("utf8"), salt, 100, dklen=32)
    
    # Encrypt password
    cipher = Cipher(algorithms.AES(key),
                    modes.CBC(iv),
                    backend=default_backend())
    encryptor = cipher.encryptor()
    ciphertext = encryptor.update(pad_password(password)) + encryptor.finalize()

    # Encode to Base64
    ciphertext_b64 = base64.b64encode(ciphertext)

    return ciphertext_b64

my_ip="10.x.x.x"
my_password="hunter2"
print(encrypt_password(my_ip, my_password, salt, iv))
```

Now it should just be a matter of finding a good way to get your IP address and updating the existing script.

**Comment by joaormatos** [comment]
I got it working and opened a pull request. #6 

Thank you @ravemir for making and maintaining this project!

**Comment by ravemir** [comment]
No problem! I actually only check it every once in a while, so apologies if things actually seemed a bit stale.

Going to review the code and accept it if everything checks out.

**Comment by tiagoduarte21** [comment]
I couldn't get it to work. It throws an error encrypting the password:

Thanks for the quick answers though!! 

```
Traceback (most recent call last):
  File "meo_wifi_login.new.py", line 109, in <module>
    main()
  File "meo_wifi_login.new.py", line 106, in main
    print meo_wifi_login(user,passwd)
  File "meo_wifi_login.new.py", line 65, in meo_wifi_login
    encrypted_password = encrypt_password(ip, password)
  File "meo_wifi_login.new.py", line 33, in encrypt_password
    modes.CBC(iv),
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/primitives/ciphers/modes.py", line 92, in __init__
    **raise TypeError("initialization_vector must be bytes")
TypeError: initialization_vector must be bytes**
```

**Comment by joaormatos** [comment]
@ravemir Thanks!

@tduarte21 Seems like you're using an older version of the cryptography library that required the iv to strictly be bytes and not "bytes-like" as the newer versions, so it doesn't take bytearray.
[This should fix it.](https://github.com/joaormatos/meo-wifi-login/commit/f9c7fff9db47b6c0cac8167fb9352bd34e055709)

**Comment by tiagoduarte21** [comment]
@joaormatos It still doesn't work (`ValueError: Invalid IV size (32) for CBC`)
But I can try to update. Which version are you using?

**Comment by joaormatos** [comment]
@tduarte21 I'm using the one in Debian 10, which seems to be  2.6.1.
The latest should work, too.

**Comment by joaormatos** [comment]
@tduarte21 Did you perhaps change it manually and ended up writing

```python
iv = bytes("72c4721ae01ae0e8e84bd64ad66060c4")
```

instead of this?:

```python
iv = bytes(bytearray.fromhex("72c4721ae01ae0e8e84bd64ad66060c4"))
```

Because otherwise I don't know how `len(iv)` could be 32 and not 16.

**Comment by tiagoduarte21** [comment]
@joaormatos yeah, that was it. I can confirm this is working now. Thank you!

**Comment by joaormatos** [comment]
In case anyone had trouble with the script yesterday, I think it was because they changed the name of one of the login parameters (navigatorLang to browserLang), but they've changed it back meanwhile.

I get the feeling that they're still fiddling around with the login system and someone deployed to production prematurely.

**Comment by joaormatos** [comment]
And... it's broken again.
Well, it's broken if your password is within certain size ranges.

Basically, they now require the password parameter to be URL-encoded.
That means the current script is going to break due to the base64 padding (unless the length of the password is between (k\*64)+32 and (k\*64)+47, for k>=0)

I'll push a fix to my repo shortly.

**Comment by ravemir** [comment]
Sorry for (yet another) big delay, guys. @joaormatos , I see you pushed [this commit](https://github.com/joaormatos/meo-wifi-login/commit/5d3908b56e1db6a1b80e1015c02ee238072c85ea) onto your forked repo.

Does this mean that passwords are now also URL encoded and correctly encrypted using the aforementioned PBKDF2 scheme?

**Comment by joaormatos** [comment]
>Does this mean that passwords are now also URL encoded and correctly encrypted using the aforementioned PBKDF2 scheme?

Last I checked, that was still the case.
I've been using it on a daily basis since September 18 and haven't had any issues since then.

**Comment by ravemir** [comment]
Fixed on PRs #6 and #10. Thanks again, @joaormatos!
